
 FROM ubuntu:22.04
 
 # Evitar archivos .pyc y buffering
 ENV DEBIAN_FRONTEND=noninteractive
 ENV PYTHONDONTWRITEBYTECODE=1
 ENV PYTHONUNBUFFERED=1
 
 # Instalar dependencias del sistema y librerías de python en una sola capa para optimizar el tamaño de la imagen
 RUN apt-get update && apt-get install -y --no-install-recommends      python3      python3-pip      python3-dev      build-essential      kicad      && pip3 install --no-cache-dir pandas numpy matplotlib requests beautifulsoup4 pypdf opencv-python-headless skidl pathfinding      && apt-get purge -y --auto-remove python3-dev build-essential      && apt-get clean      && rm -rf /var/lib/apt/lists/*
 
 # Asegurar que 'python' apunte a python3 para compatibilidad
 RUN ln -s /usr/bin/python3 /usr/bin/python
 
 WORKDIR /app
 