#!/usr/bin/env python3
"""
Genera un script Python que, al ser ejecutado dentro de la Consola de Scripting
de KiCad PCB Editor (pcbnew), crea un archivo .kicad_pcb con los componentes
colocados y las conexiones (ratsnest) definidas a partir de un JSON de diseño.
"""
import json
import argparse
import os
import sys

# Este script NO importa pcbnew directamente, ya que está diseñado para
# generar otro script que SÍ lo importará dentro de KiCad.

def generate_pcb_script(design_json_path, output_script_path):
    """
    Crea un script Python para KiCad PCB Editor.
    """
    # Cargar el JSON de diseño
    try:
        with open(design_json_path, 'r') as f:
            design_data = json.load(f)
    except Exception as e:
        print(json.dumps({"status": "error", "message": f"Error leyendo JSON de diseño: {e}"}))
        sys.exit(1)

    components = design_data.get("components", [])
    netlist_data = design_data.get("netlist", [])

    # Construir un mapa de cuántos pines necesita cada componente (para fallback)
    pins_per_ref = {}
    for net_info in netlist_data:
        for node in net_info.get('nodes', []):
            parts = node.split('-')
            if len(parts) == 2:
                ref, pin = parts
                if ref not in pins_per_ref:
                    pins_per_ref[ref] = set()
                pins_per_ref[ref].add(pin)
    # Inyectar el mapa como dato en el script generado
    pins_per_ref_serializable = {k: sorted(list(v)) for k, v in pins_per_ref.items()}

    # Generar el contenido del script de KiCad
    script_lines = [
        "import os",
        "import json",
        "import sys",
        "import subprocess",
        "import time",
        "import math",
        "",
        "# --- Configuración de Entorno Gráfico (Headless) ---",
        "# Iniciamos Xvfb para que KiCad/pcbnew tenga un 'monitor' donde operar",
        "os.environ['DISPLAY'] = ':99'",
        "xvfb_proc = None",
        "try:",
        "    if os.system('pgrep Xvfb > /dev/null') != 0:",
        "        print('Iniciando servidor gráfico virtual (Xvfb)...', file=sys.stderr)",
        "        xvfb_proc = subprocess.Popen(['Xvfb', ':99', '-screen', '0', '1024x768x24', '-ac', '+extension', 'GLX', '+render', '-noreset'])",
        "        time.sleep(3) # Esperar a que Xvfb arranque",
        "        if xvfb_proc and xvfb_proc.poll() is not None:",
        "            print(f'Error: Xvfb terminó inesperadamente. Código: {xvfb_proc.returncode}', file=sys.stderr)",
        "            sys.exit(1)",
        "except Exception as e:",
        "    print(f'Error fatal al iniciar Xvfb: {e}', file=sys.stderr)",
        "    sys.exit(1)",
        "",
        "try:",
        "    print('Intentando importar pcbnew...', file=sys.stderr)",
        "    import pcbnew",
        "    print('pcbnew importado con éxito.', file=sys.stderr)",
        "except Exception as e:",
        "    print(f'Error: No se pudo importar pcbnew. Verifica la instalación de KiCad. Error: {e}', file=sys.stderr)",
        "    import traceback; traceback.print_exc(file=sys.stderr)",
        "    sys.exit(1)",
        "",
        "try:",
        "    from pathfinding.core.diagonal_movement import DiagonalMovement",
        "    from pathfinding.core.grid import Grid",
        "    from pathfinding.finder.a_star import AStarFinder",
        "    PATHFINDING_AVAILABLE = True",
        "except ImportError:",
        "    PATHFINDING_AVAILABLE = False",
        "",
        "# --- Configuración de la Placa ---",
        "BOARD_WIDTH_MM = 150",
        "BOARD_HEIGHT_MM = 100",
        "GRID_SPACING_X_MM = 30",
        "GRID_SPACING_Y_MM = 30",
        "START_X_MM = 25",
        "START_Y_MM = 25",
        "",
        "# --- Helper para convertir mm a unidades internas de KiCad (nanómetros) ---",
        "def mm_to_nm(mm_val):",
        "    return int(mm_val * 1000000)",
        "",
        "# --- Crear una nueva placa ---",
        "board = pcbnew.BOARD()",
        "",
        "# --- Definir el contorno de la placa (Edge.Cuts) ---",
        "edge_layer = pcbnew.Edge_Cuts",
        "board_outline = pcbnew.PCB_SHAPE(board)",
        "board_outline.SetShape(pcbnew.SHAPE_T_RECT)",
        "board_outline.SetStart(pcbnew.VECTOR2I(mm_to_nm(0), mm_to_nm(0)))",
        "board_outline.SetEnd(pcbnew.VECTOR2I(mm_to_nm(BOARD_WIDTH_MM), mm_to_nm(BOARD_HEIGHT_MM)))",
        "board_outline.SetLayer(edge_layer)",
        "board.Add(board_outline)",
        "",
        "# --- Datos de componentes y netlist (inyectados desde el JSON original) ---",
        f"components_data = {json.dumps(components, indent=2)}",
        f"netlist_data = {json.dumps(netlist_data, indent=2)}",
        f"pins_per_ref = {json.dumps(pins_per_ref_serializable, indent=2)}",
        "",
        "# --- Helper: Crear footprint genérico con pads reales ---",
        "def create_generic_footprint(board, ref, pin_list, pos_x_nm, pos_y_nm):",
        "    fp = pcbnew.FOOTPRINT(board)",
        "    fp.SetReference(ref)",
        "    fp.SetPosition(pcbnew.VECTOR2I(pos_x_nm, pos_y_nm))",
        "    fp.SetLayer(pcbnew.F_Cu)",
        "    # Crear pads reales para cada pin (espaciados 2.54mm = paso THT estándar)",
        "    pad_pitch_nm = mm_to_nm(2.54)",
        "    pad_size_nm = mm_to_nm(1.6)",
        "    drill_nm = mm_to_nm(0.8)",
        "    n_pins = len(pin_list) if pin_list else 2",
        "    for idx, pin_num in enumerate(pin_list if pin_list else ['1', '2']):",
        "        pad = pcbnew.PAD(fp)",
        "        pad.SetNumber(str(pin_num))",
        "        pad.SetShape(pcbnew.PAD_SHAPE_CIRCLE)",
        "        pad.SetAttribute(pcbnew.PAD_ATTRIB_PTH)  # Through-hole",
        "        pad.SetSize(pcbnew.VECTOR2I(pad_size_nm, pad_size_nm))",
        "        pad.SetDrillSize(pcbnew.VECTOR2I(drill_nm, drill_nm))",
        "        # Offset pads horizontalmente desde el centro del footprint",
        "        offset_x = int((idx - (n_pins - 1) / 2.0) * pad_pitch_nm) if n_pins > 1 else 0",
        "        pad.SetPosition(pcbnew.VECTOR2I(pos_x_nm + offset_x, pos_y_nm))",
        "        pad.SetLayerSet(pcbnew.LSET.PTHMask())",
        "        fp.Add(pad)",
        "    board.Add(fp)",
        "    return fp",
        "",
        "# --- Cargar y colocar Footprints (Huellas) ---",
        "footprints_by_ref = {}",
        "for i, comp in enumerate(components_data):",
        "    ref = comp['ref']",
        "    pin_list = pins_per_ref.get(ref, ['1', '2'])",
        "    if 'footprint' in comp and comp['footprint']:",
        "        footprint_name = comp['footprint']",
        "    else:",
        "        ctype = str(comp.get('type', '')).upper()",
        "        cval = str(comp.get('value', '')).lower()",
        "        # IMPORTANT: check capacitors/LEDs/pots BEFORE ICs to avoid 'IC' substring in 'ELECTROLYTIC','CERAMIC'",
        "        if ref.startswith('C') or 'CAP' in ctype:",
        "            footprint_name = 'Capacitor_THT:CP_Radial_D5.0mm_P2.50mm' if 'uf' in cval else 'Capacitor_THT:C_Disc_D5.0mm_W2.5mm_P5.00mm'",
        "        elif ref.startswith('D') or 'LED' in ctype or 'DIOD' in ctype:",
        "            footprint_name = 'LED_THT:LED_D5.0mm'",
        "        elif ref.startswith('RV') or 'POT' in ctype:",
        "            footprint_name = 'Potentiometer_THT:Potentiometer_Alps_RK163_Single_Horizontal'",
        "        elif ref.startswith('R'):",
        "            footprint_name = 'Resistor_THT:R_Axial_DIN0207_L6.3mm_D2.5mm_P7.62mm_Horizontal'",
        "        elif ref.startswith('Q') or 'TRANS' in ctype:",
        "            footprint_name = 'Package_TO_SOT_THT:TO-92_Inline'",
        "        elif ref.startswith('U') or 'IC' in ctype or ctype == 'MICROCONTROLLER':",
        "            npins = len(pin_list)",
        "            if npins < 4: npins = 8",
        "            if npins % 2 != 0: npins += 1",
        "            footprint_name = f'Package_DIP:DIP-{npins}_W7.62mm'",
        "        else:",
        "            footprint_name = 'Resistor_THT:R_Axial_DIN0207_L6.3mm_D2.5mm_P7.62mm_Horizontal'",
        "    ",
        "    # Calcular posición en una cuadrícula simple",
        "    col = i % (BOARD_WIDTH_MM // GRID_SPACING_X_MM)",
        "    row = i // (BOARD_WIDTH_MM // GRID_SPACING_X_MM)",
        "    pos_x_mm = START_X_MM + col * GRID_SPACING_X_MM",
        "    pos_y_mm = START_Y_MM + row * GRID_SPACING_Y_MM",
        "    ",
        "    # Intentar cargar la huella desde las librerías de KiCad",
        "    pos_x_nm = mm_to_nm(pos_x_mm)",
        "    pos_y_nm = mm_to_nm(pos_y_mm)",
        "    try:",
        "        fp = None",
        "        footprint_lib_id = footprint_name.split(':', 1)",
        "        if len(footprint_lib_id) == 2:",
        "            lib_name, fp_name = footprint_lib_id",
        "            lib_path = f'/usr/share/kicad/footprints/{lib_name}.pretty'",
        "            import os as _os",
        "            if _os.path.exists(lib_path):",
        "                fp = pcbnew.FootprintLoad(lib_path, fp_name)",
        "            else:",
        "                print(f'  ⚠️ Librería no encontrada: {lib_path}')",
        "        ",
        "        if fp is None:",
        "            raise Exception(f'FootprintLoad devolvió None para {footprint_name}')",
        "        ",
        "        fp.SetReference(ref)",
        "        fp.SetPosition(pcbnew.VECTOR2I(pos_x_nm, pos_y_nm))",
        "        fp.SetLayer(pcbnew.F_Cu)",
        "        board.Add(fp)",
        "        footprints_by_ref[ref] = fp",
        "        print(f'✅ Footprint {ref} ({footprint_name}) colocado en ({pos_x_mm:.2f}, {pos_y_mm:.2f})')",
        "    except Exception as e:",
        "        print(f'⚠️ Fallback genérico para {ref}: {e}')",
        "        fp = create_generic_footprint(board, ref, pin_list, pos_x_nm, pos_y_nm)",
        "        footprints_by_ref[ref] = fp",
        "        print(f'📦 Footprint genérico {ref} con pads {pin_list} colocado en ({pos_x_mm:.2f}, {pos_y_mm:.2f})')",
        "",
        "# --- Crear Netlist y conectar Pads ---",
        "nets_by_name = {}",
        "for net_info in netlist_data:",
        "    net_name = net_info.get('net_name') or net_info.get('netname')",
        "    if net_name not in nets_by_name:",
        "        net = pcbnew.NETINFO_ITEM(board, net_name)",
        "        board.Add(net)",
        "        nets_by_name[net_name] = net",
        "    else:",
        "        net = nets_by_name[net_name]",
        "    ",
        "    for node in net_info['nodes']:",
        "        if '-' not in str(node):",
        "            print(f'  ⚠️ Saltando nodo inválido (formato incorrecto): {node}')",
        "            continue",
        "        ref, pin_num = node.split('-', 1)",
        "        if ref in footprints_by_ref:",
        "            fp = footprints_by_ref[ref]",
        "            pad = fp.FindPadByNumber(pin_num)",
        "            if not pad:",
        "                pnum_u = pin_num.upper()",
        "                if pnum_u == 'ANODE': pad = fp.FindPadByNumber('2') or fp.FindPadByNumber('A') or fp.FindPadByNumber('1')",
        "                elif pnum_u == 'CATHODE': pad = fp.FindPadByNumber('1') or fp.FindPadByNumber('K') or fp.FindPadByNumber('2')",
        "                elif pnum_u in ('POS', '+'): pad = fp.FindPadByNumber('2') or fp.FindPadByNumber('1')",
        "                elif pnum_u in ('NEG', '-'): pad = fp.FindPadByNumber('1') or fp.FindPadByNumber('2')",
        "                else:",
        "                    import re",
        "                    m = re.search(r'\\d+', pin_num)",
        "                    if m: pad = fp.FindPadByNumber(m.group(0))",
        "            if pad:",
        "                pad.SetNetCode(net.GetNetCode())",
        "            else:",
        "                print(f'Warning: Pad {pin_num} not found for {ref}.')",
        "        else:",
        "            print(f'Warning: Footprint {ref} not found in placed components for net {net_name}.')",
        "",
        "# --- Auto-Enrutado con A* + Fallback L-Shape ---",
        "if PATHFINDING_AVAILABLE:",
        "    print('🚀 Iniciando Auto-Enrutado con algoritmo A*...')",
        "    RESOLUTION = 0.5 # mm por celda",
        "    cols = int(BOARD_WIDTH_MM / RESOLUTION)",
        "    rows = int(BOARD_HEIGHT_MM / RESOLUTION)",
        "    PAD_CLEARANCE_RADIUS = 3  # celdas de radio para liberar alrededor de cada pad endpoint",
        "    ",
        "    # Construir la matriz base de obstáculos (solo los cuerpos de los footprints)",
        "    # Se bloquean los pads con padding=1, pero se liberarán los endpoints antes de cada búsqueda",
        "    base_matrix = [[1 for _ in range(cols)] for _ in range(rows)]",
        "    for ref_fp, fp_obs in footprints_by_ref.items():",
        "        for pad_obs in fp_obs.Pads():",
        "            pos_obs = pad_obs.GetPosition()",
        "            c_obs = int(pcbnew.ToMM(pos_obs.x) / RESOLUTION)",
        "            r_obs = int(pcbnew.ToMM(pos_obs.y) / RESOLUTION)",
        "            padding = 1",
        "            for dx in range(-padding, padding + 1):",
        "                for dy in range(-padding, padding + 1):",
        "                    nx, ny = c_obs + dx, r_obs + dy",
        "                    if 0 <= nx < cols and 0 <= ny < rows:",
        "                        base_matrix[ny][nx] = 0",
        "    ",
        "    routed_count = 0",
        "    failed_count = 0",
        "    total_connections = 0",
        "    routed_tracks_cells = []  # track cells for marking as obstacles later",
        "    ",
        "    # Helper: add an L-shaped (Manhattan) track between two pads as fallback",
        "    def add_l_route(board_ref, p1_pos, p2_pos, net_ref, width_nm, layer):",
        "        mid = pcbnew.VECTOR2I(p2_pos.x, p1_pos.y)  # horizontal then vertical",
        "        t1 = pcbnew.PCB_TRACK(board_ref)",
        "        t1.SetStart(p1_pos)",
        "        t1.SetEnd(mid)",
        "        t1.SetWidth(width_nm)",
        "        t1.SetLayer(layer)",
        "        t1.SetNet(net_ref)",
        "        board_ref.Add(t1)",
        "        t2 = pcbnew.PCB_TRACK(board_ref)",
        "        t2.SetStart(mid)",
        "        t2.SetEnd(p2_pos)",
        "        t2.SetWidth(width_nm)",
        "        t2.SetLayer(layer)",
        "        t2.SetNet(net_ref)",
        "        board_ref.Add(t2)",
        "    ",
        "    for net_name, net in nets_by_name.items():",
        "        pads = []",
        "        for ref_fp, fp_rt in footprints_by_ref.items():",
        "            for pad_rt in fp_rt.Pads():",
        "                if pad_rt.GetNetCode() == net.GetNetCode():",
        "                    pads.append(pad_rt)",
        "        if len(pads) < 2: continue",
        "        total_connections += len(pads) - 1",
        "        pads.sort(key=lambda p: p.GetPosition().x)",
        "        ",
        "        track_width = 0.8 if any(x in net_name.upper() for x in ['VCC', 'GND', '+', 'PWR', 'BAT']) else 0.4",
        "        width_nm = mm_to_nm(track_width)",
        "        ",
        "        for i in range(len(pads) - 1):",
        "            p1 = pads[i]",
        "            p2 = pads[i+1]",
        "            p1_pos = p1.GetPosition()",
        "            p2_pos = p2.GetPosition()",
        "            c1 = max(0, min(cols - 1, int(pcbnew.ToMM(p1_pos.x) / RESOLUTION)))",
        "            r1 = max(0, min(rows - 1, int(pcbnew.ToMM(p1_pos.y) / RESOLUTION)))",
        "            c2 = max(0, min(cols - 1, int(pcbnew.ToMM(p2_pos.x) / RESOLUTION)))",
        "            r2 = max(0, min(rows - 1, int(pcbnew.ToMM(p2_pos.y) / RESOLUTION)))",
        "            ",
        "            # Build a fresh copy of the base matrix for this connection",
        "            import copy",
        "            work_matrix = copy.deepcopy(base_matrix)",
        "            ",
        "            # Mark previously routed tracks as obstacles",
        "            for tc in routed_tracks_cells:",
        "                if 0 <= tc[0] < cols and 0 <= tc[1] < rows:",
        "                    work_matrix[tc[1]][tc[0]] = 0",
        "            ",
        "            # Clear a corridor around start and end so A* can escape the pad cluster",
        "            for cx, ry in [(c1, r1), (c2, r2)]:",
        "                for dx in range(-PAD_CLEARANCE_RADIUS, PAD_CLEARANCE_RADIUS + 1):",
        "                    for dy in range(-PAD_CLEARANCE_RADIUS, PAD_CLEARANCE_RADIUS + 1):",
        "                        nx, ny = cx + dx, ry + dy",
        "                        if 0 <= nx < cols and 0 <= ny < rows:",
        "                            work_matrix[ny][nx] = 1",
        "            ",
        "            grid = Grid(matrix=work_matrix)",
        "            finder = AStarFinder(diagonal_movement=DiagonalMovement.always)",
        "            ",
        "            try:",
        "                path, runs = finder.find_path(grid.node(c1, r1), grid.node(c2, r2), grid)",
        "            except Exception:",
        "                path = []",
        "            ",
        "            if path and len(path) > 1:",
        "                # Simplify colinear segments",
        "                if len(path) > 2:",
        "                    simplified = [path[0]]",
        "                    last_dir = (path[1].x - path[0].x, path[1].y - path[0].y)",
        "                    for k in range(2, len(path)):",
        "                        curr_dir = (path[k].x - path[k-1].x, path[k].y - path[k-1].y)",
        "                        if curr_dir != last_dir:",
        "                            simplified.append(path[k-1])",
        "                            last_dir = curr_dir",
        "                    simplified.append(path[-1])",
        "                    path = simplified",
        "                ",
        "                routed_count += 1",
        "                print(f'  ✅ Ruta A* trazada para {net_name}: {len(path)} puntos')",
        "                for j in range(len(path) - 1):",
        "                    s = path[j]",
        "                    e = path[j+1]",
        "                    track = pcbnew.PCB_TRACK(board)",
        "                    track.SetStart(pcbnew.VECTOR2I(mm_to_nm(s.x*RESOLUTION), mm_to_nm(s.y*RESOLUTION)))",
        "                    track.SetEnd(pcbnew.VECTOR2I(mm_to_nm(e.x*RESOLUTION), mm_to_nm(e.y*RESOLUTION)))",
        "                    track.SetWidth(width_nm)",
        "                    track.SetLayer(pcbnew.F_Cu)",
        "                    track.SetNet(net)",
        "                    board.Add(track)",
        "                # Record cells along path as obstacles for future routes",
        "                for node_cell in path:",
        "                    routed_tracks_cells.append((node_cell.x, node_cell.y))",
        "            else:",
        "                # Fallback: L-shaped Manhattan route (guaranteed connection)",
        "                routed_count += 1",
        "                print(f'  🔀 Ruta L-shape (fallback) trazada para {net_name}')",
        "                add_l_route(board, p1_pos, p2_pos, net, width_nm, pcbnew.F_Cu)",
        "",
        "else:",
        "    print('ℹ️ Módulo pathfinding no disponible. Se omite el auto-enrutado.')",
        "    print('  📎 Las conexiones quedan como ratsnest; se pueden enrutar manualmente en KiCad.')",
        "",
        "# --- Validación DRC (Design Rules Check) ---",
        "def check_drc(board, min_clearance_mm=0.3):",
        "    print(f'🔍 Ejecutando DRC (Clearance: {min_clearance_mm}mm)...')",
        "    min_dist_nm = mm_to_nm(min_clearance_mm)",
        "    violations = 0",
        "    tracks = [t for t in board.GetTracks() if t.GetClass() == 'PCB_TRACK']",
        "    footprints = list(board.GetFootprints())",
        "    for track in tracks:",
        "        t_start = track.GetStart()",
        "        t_end = track.GetEnd()",
        "        t_width = track.GetWidth()",
        "        t_net = track.GetNetCode()",
        "        for fp in footprints:",
        "            for pad in fp.Pads():",
        "                if pad.GetNetCode() == t_net: continue",
        "                p_pos = pad.GetPosition()",
        "                # Distancia punto a segmento",
        "                seg_v_x = t_end.x - t_start.x",
        "                seg_v_y = t_end.y - t_start.y",
        "                pt_v_x = p_pos.x - t_start.x",
        "                pt_v_y = p_pos.y - t_start.y",
        "                seg_len_sq = seg_v_x**2 + seg_v_y**2",
        "                if seg_len_sq == 0: dist_sq = pt_v_x**2 + pt_v_y**2",
        "                else:",
        "                    t = max(0, min(1, (pt_v_x * seg_v_x + pt_v_y * seg_v_y) / float(seg_len_sq)))",
        "                    proj_x = int(t_start.x + t * seg_v_x)",
        "                    proj_y = int(t_start.y + t * seg_v_y)",
        "                    dist_sq = (p_pos.x - proj_x)**2 + (p_pos.y - proj_y)**2",
        "                dist = math.sqrt(dist_sq)",
        "                p_radius = min(pad.GetSize().x, pad.GetSize().y) / 2",
        "                t_radius = t_width / 2",
        "                if dist < (p_radius + t_radius + min_dist_nm):",
        "                    violations += 1",
        "    if violations > 0:",
        "        print(f'❌ DRC FALLÓ: {violations} violaciones detectadas (Posibles cortocircuitos).')",
        "    else:",
        "        print('✅ DRC PASÓ: Diseño seguro para CNC.')",
        "",
        "# --- Guardar la placa ---",
        "output_dir = '/mnt/out' if os.path.exists('/mnt/out') else os.path.dirname(os.path.abspath(__file__))",
        "output_filename = os.path.join(output_dir, 'circuito_generado.kicad_pcb')",
        "try:",
        "    check_drc(board)",
        "    pcbnew.SaveBoard(output_filename, board)",
        "    print(f'✅ PCB guardado en: {output_filename}')",
        "except Exception as e:",
        "    print(f'❌ Error guardando PCB: {e}', file=sys.stderr)",
        "    sys.exit(1)",
        "",
        "if PATHFINDING_AVAILABLE:",
        "    print(f'ROUTING_SUMMARY:Routed={routed_count},Failed={failed_count},Total={total_connections}')",
        "else:",
        "    print(f'ROUTING_SUMMARY:Routed=0,Failed=0,Total=0')",
        "",
        "if xvfb_proc: xvfb_proc.terminate()",
    ]

    # Escribir el script generado en el archivo de salida
    try:
        os.makedirs(os.path.dirname(output_script_path) or ".", exist_ok=True)
        with open(output_script_path, 'w') as f:
            f.write("\n".join(script_lines))
        print(json.dumps({"status": "success", "file": output_script_path}))
    except Exception as e:
        print(json.dumps({"status": "error", "message": f"Error escribiendo script de PCB: {e}"}))
        sys.exit(1)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Genera un script Python para crear un archivo KiCad PCB (.kicad_pcb).")
    parser.add_argument("--json", required=True, help="Ruta al archivo JSON de diseño.")
    parser.add_argument("--output", required=True, help="Ruta de salida para el script Python generado.")
    args = parser.parse_args()

    generate_pcb_script(args.json, args.output)