#!/usr/bin/env python3
"""
Genera un script Python que, al ser ejecutado dentro de la Consola de Scripting
de KiCad PCB Editor (pcbnew), crea un archivo .kicad_pcb con los componentes
colocados y las conexiones (ratsnest) definidas a partir de un JSON de diseño.
"""
import json
import argparse
import os
import sys

# Este script NO importa pcbnew directamente, ya que está diseñado para
# generar otro script que SÍ lo importará dentro de KiCad.

def generate_pcb_script(design_json_path, output_script_path):
    """
    Crea un script Python para KiCad PCB Editor.
    """
    # Cargar el JSON de diseño
    try:
        with open(design_json_path, 'r') as f:
            design_data = json.load(f)
    except Exception as e:
        print(json.dumps({"status": "error", "message": f"Error leyendo JSON de diseño: {e}"}))
        sys.exit(1)

    components = design_data.get("components", [])
    netlist_data = design_data.get("netlist", [])

    # Construir un mapa de cuántos pines necesita cada componente (para fallback)
    pins_per_ref = {}
    for net_info in netlist_data:
        for node in net_info.get('nodes', []):
            parts = node.split('-')
            if len(parts) == 2:
                ref, pin = parts
                if ref not in pins_per_ref:
                    pins_per_ref[ref] = set()
                pins_per_ref[ref].add(pin)
    # Inyectar el mapa como dato en el script generado
    pins_per_ref_serializable = {k: sorted(list(v)) for k, v in pins_per_ref.items()}

    # Generar el contenido del script de KiCad
    script_lines = [
        "import os",
        "import json",
        "import sys",
        "import subprocess",
        "import time",
        "import math",
        "",
        "# --- Configuración de Entorno Gráfico (Headless) ---",
        "# Iniciamos Xvfb para que KiCad/pcbnew tenga un 'monitor' donde operar",
        "os.environ['DISPLAY'] = ':99'",
        "xvfb_proc = None",
        "try:",
        "    if os.system('pgrep Xvfb > /dev/null') != 0:",
        "        print('Iniciando servidor gráfico virtual (Xvfb)...', file=sys.stderr)",
        "        xvfb_proc = subprocess.Popen(['Xvfb', ':99', '-screen', '0', '1024x768x24', '-ac', '+extension', 'GLX', '+render', '-noreset'])",
        "        time.sleep(3) # Esperar a que Xvfb arranque",
        "        if xvfb_proc and xvfb_proc.poll() is not None:",
        "            print(f'Error: Xvfb terminó inesperadamente. Código: {xvfb_proc.returncode}', file=sys.stderr)",
        "            sys.exit(1)",
        "except Exception as e:",
        "    print(f'Error fatal al iniciar Xvfb: {e}', file=sys.stderr)",
        "    sys.exit(1)",
        "",
        "try:",
        "    print('Intentando importar pcbnew...', file=sys.stderr)",
        "    import pcbnew",
        "    print('pcbnew importado con éxito.', file=sys.stderr)",
        "except Exception as e:",
        "    print(f'Error: No se pudo importar pcbnew. Verifica la instalación de KiCad. Error: {e}', file=sys.stderr)",
        "    import traceback; traceback.print_exc(file=sys.stderr)",
        "    sys.exit(1)",
        "",
        "try:",
        "    from pathfinding.core.diagonal_movement import DiagonalMovement",
        "    from pathfinding.core.grid import Grid",
        "    from pathfinding.finder.a_star import AStarFinder",
        "    PATHFINDING_AVAILABLE = True",
        "except ImportError:",
        "    PATHFINDING_AVAILABLE = False",
        "",
        "# --- Configuración de la Placa ---",
        "BOARD_WIDTH_MM = 100",
        "BOARD_HEIGHT_MM = 70",
        "GRID_SPACING_X_MM = 25",
        "GRID_SPACING_Y_MM = 25",
        "START_X_MM = 20",
        "START_Y_MM = 20",
        "",
        "# --- Helper para convertir mm a unidades internas de KiCad (nanómetros) ---",
        "def mm_to_nm(mm_val):",
        "    return int(mm_val * 1000000)",
        "",
        "# --- Crear una nueva placa ---",
        "board = pcbnew.BOARD()",
        "",
        "# --- Definir el contorno de la placa (Edge.Cuts) ---",
        "edge_layer = pcbnew.Edge_Cuts",
        "board_outline = pcbnew.PCB_SHAPE(board)",
        "board_outline.SetShape(pcbnew.SHAPE_T_RECT)",
        "board_outline.SetStart(pcbnew.VECTOR2I(mm_to_nm(0), mm_to_nm(0)))",
        "board_outline.SetEnd(pcbnew.VECTOR2I(mm_to_nm(BOARD_WIDTH_MM), mm_to_nm(BOARD_HEIGHT_MM)))",
        "board_outline.SetLayer(edge_layer)",
        "board.Add(board_outline)",
        "",
        "# --- Datos de componentes y netlist (inyectados desde el JSON original) ---",
        f"components_data = {json.dumps(components, indent=2)}",
        f"netlist_data = {json.dumps(netlist_data, indent=2)}",
        f"pins_per_ref = {json.dumps(pins_per_ref_serializable, indent=2)}",
        "",
        "# --- Helper: Crear footprint genérico con pads reales ---",
        "def create_generic_footprint(board, ref, pin_list, pos_x_nm, pos_y_nm):",
        "    fp = pcbnew.FOOTPRINT(board)",
        "    fp.SetReference(ref)",
        "    fp.SetPosition(pcbnew.VECTOR2I(pos_x_nm, pos_y_nm))",
        "    fp.SetLayer(pcbnew.F_Cu)",
        "    # Crear pads reales para cada pin (espaciados 2.54mm = paso THT estándar)",
        "    pad_pitch_nm = mm_to_nm(2.54)",
        "    pad_size_nm = mm_to_nm(1.6)",
        "    drill_nm = mm_to_nm(0.8)",
        "    n_pins = len(pin_list) if pin_list else 2",
        "    for idx, pin_num in enumerate(pin_list if pin_list else ['1', '2']):",
        "        pad = pcbnew.PAD(fp)",
        "        pad.SetNumber(str(pin_num))",
        "        pad.SetShape(pcbnew.PAD_SHAPE_CIRCLE)",
        "        pad.SetAttribute(pcbnew.PAD_ATTRIB_PTH)  # Through-hole",
        "        pad.SetSize(pcbnew.VECTOR2I(pad_size_nm, pad_size_nm))",
        "        pad.SetDrillSize(pcbnew.VECTOR2I(drill_nm, drill_nm))",
        "        # Offset pads horizontalmente desde el centro del footprint",
        "        offset_x = int((idx - (n_pins - 1) / 2.0) * pad_pitch_nm)",
        "        pad.SetPosition(pcbnew.VECTOR2I(pos_x_nm + offset_x, pos_y_nm))",
        "        pad.SetLayerSet(pcbnew.PAD.PTHMask())",
        "        fp.Add(pad)",
        "    board.Add(fp)",
        "    return fp",
        "",
        "# --- Cargar y colocar Footprints (Huellas) ---",
        "footprints_by_ref = {}",
        "for i, comp in enumerate(components_data):",
        "    ref = comp['ref']",
        "    footprint_name = comp.get('footprint', 'Resistor_THT:R_Axial_DIN0207_L6.3mm_D2.5mm_P7.62mm_Horizontal') # Nombre de la huella",
        "    ",
        "    # Calcular posición en una cuadrícula simple",
        "    col = i % (BOARD_WIDTH_MM // GRID_SPACING_X_MM)",
        "    row = i // (BOARD_WIDTH_MM // GRID_SPACING_X_MM)",
        "    pos_x_mm = START_X_MM + col * GRID_SPACING_X_MM",
        "    pos_y_mm = START_Y_MM + row * GRID_SPACING_Y_MM",
        "    ",
        "    # Intentar cargar la huella desde las librerías de KiCad",
        "    pos_x_nm = mm_to_nm(pos_x_mm)",
        "    pos_y_nm = mm_to_nm(pos_y_mm)",
        "    pin_list = pins_per_ref.get(ref, ['1', '2'])",
        "    try:",
        "        fp = None",
        "        footprint_lib_id = footprint_name.split(':', 1)",
        "        if len(footprint_lib_id) == 2:",
        "            lib_name, fp_name = footprint_lib_id",
        "            lib_path = f'/usr/share/kicad/footprints/{lib_name}.pretty'",
        "            import os as _os",
        "            if _os.path.exists(lib_path):",
        "                fp = pcbnew.FootprintLoad(lib_path, fp_name)",
        "            else:",
        "                print(f'  ⚠️ Librería no encontrada: {lib_path}')",
        "        ",
        "        if fp is None:",
        "            raise Exception(f'FootprintLoad devolvió None para {footprint_name}')",
        "        ",
        "        fp.SetReference(ref)",
        "        fp.SetPosition(pcbnew.VECTOR2I(pos_x_nm, pos_y_nm))",
        "        fp.SetLayer(pcbnew.F_Cu)",
        "        board.Add(fp)",
        "        footprints_by_ref[ref] = fp",
        "        print(f'✅ Footprint {ref} ({footprint_name}) colocado en ({pos_x_mm:.2f}, {pos_y_mm:.2f})')",
        "    except Exception as e:",
        "        print(f'⚠️ Fallback genérico para {ref}: {e}')",
        "        fp = create_generic_footprint(board, ref, pin_list, pos_x_nm, pos_y_nm)",
        "        footprints_by_ref[ref] = fp",
        "        print(f'📦 Footprint genérico {ref} con pads {pin_list} colocado en ({pos_x_mm:.2f}, {pos_y_mm:.2f})')",
        "",
        "# --- Crear Netlist y conectar Pads ---",
        "nets_by_name = {}",
        "for net_info in netlist_data:",
        "    net_name = net_info.get('net_name') or net_info.get('netname')",
        "    if net_name not in nets_by_name:",
        "        net = pcbnew.NETINFO_ITEM(board, net_name)",
        "        board.Add(net)",
        "        nets_by_name[net_name] = net",
        "    else:",
        "        net = nets_by_name[net_name]",
        "    ",
        "    for node in net_info['nodes']:",
        "        ref, pin_num = node.split('-')",
        "        if ref in footprints_by_ref:",
        "            fp = footprints_by_ref[ref]",
        "            pad = fp.FindPadByNumber(pin_num)",
        "            if pad:",
        "                pad.SetNetCode(net.GetNetCode())",
        "            else:",
        "                print(f'Warning: Pad {pin_num} not found for {ref}.')",
        "        else:",
        "            print(f'Warning: Footprint {ref} not found in placed components for net {net_name}.')",
        "",
        "# --- Auto-Enrutado con A* (Experimental) ---",
        "if PATHFINDING_AVAILABLE:",
        "    print('🚀 Iniciando Auto-Enrutado con algoritmo A*...')",
        "    RESOLUTION = 0.5 # mm por celda (ajustar según precisión deseada)",
        "    cols = int(BOARD_WIDTH_MM / RESOLUTION)",
        "    rows = int(BOARD_HEIGHT_MM / RESOLUTION)",
        "    ",
        "    # Crear matriz: 1 = Transitable, 0 = Obstáculo",
        "    matrix = [[1 for _ in range(cols)] for _ in range(rows)]",
        "    ",
        "    # Marcar todos los pads como obstáculos iniciales",
        "    for ref, fp in footprints_by_ref.items():",
        "        for pad in fp.Pads():",
        "            pos = pad.GetPosition()",
        "            c = int(pcbnew.ToMM(pos.x) / RESOLUTION)",
        "            r = int(pcbnew.ToMM(pos.y) / RESOLUTION)",
        "            # Marcar celda y vecinos cercanos como obstáculo (Padding para aislamiento)",
        "            padding = 1",
        "            for dx in range(-padding, padding + 1):",
        "                for dy in range(-padding, padding + 1):",
        "                    nx, ny = c + dx, r + dy",
        "                    if 0 <= nx < cols and 0 <= ny < rows:",
        "                        matrix[ny][nx] = 0",
        "    ",
        "    grid = Grid(matrix=matrix)",
        "    finder = AStarFinder(diagonal_movement=DiagonalMovement.always)",
        "    ",
        "    routed_count = 0",
        "    failed_count = 0",
        "    total_connections = 0",
        "    ",
        "    for net_name, net in nets_by_name.items():",
        "        # Obtener pads de esta net",
        "        pads = []",
        "        for ref, fp in footprints_by_ref.items():",
        "            for pad in fp.Pads():",
        "                if pad.GetNetCode() == net.GetNetCode():",
        "                    pads.append(pad)",
        "        ",
        "        if len(pads) < 2: continue",
        "        total_connections += len(pads) - 1",
        "        ",
        "        # Ordenar pads por posición X para conectar en cadena",
        "        pads.sort(key=lambda p: p.GetPosition().x)",
        "        ",
        "        for i in range(len(pads) - 1):",
        "            p1 = pads[i]",
        "            p2 = pads[i+1]",
        "            c1, r1 = int(pcbnew.ToMM(p1.GetPosition().x)/RESOLUTION), int(pcbnew.ToMM(p1.GetPosition().y)/RESOLUTION)",
        "            c2, r2 = int(pcbnew.ToMM(p2.GetPosition().x)/RESOLUTION), int(pcbnew.ToMM(p2.GetPosition().y)/RESOLUTION)",
        "            ",
        "            # Habilitar temporalmente inicio y fin (eran obstáculos)",
        "            node_start = grid.node(c1, r1)",
        "            node_end = grid.node(c2, r2)",
        "            node_start.walkable = True",
        "            node_end.walkable = True",
        "            ",
        "            path, runs = finder.find_path(node_start, node_end, grid)",
        "            grid.cleanup() # Limpiar estado para la siguiente búsqueda",
        "            ",
        "            if path:",
        "                # --- Simplificar camino (fusionar segmentos colineales) ---",
        "                if len(path) > 2:",
        "                    simplified_path = [path[0]]",
        "                    last_dir = (path[1].x - path[0].x, path[1].y - path[0].y)",
        "                    for k in range(2, len(path)):",
        "                        curr_dir = (path[k].x - path[k-1].x, path[k].y - path[k-1].y)",
        "                        if curr_dir != last_dir:",
        "                            simplified_path.append(path[k-1])",
        "                            last_dir = curr_dir",
        "                    simplified_path.append(path[-1])",
        "                    path = simplified_path",
        "                ",
        "                routed_count += 1",
        "                print(f'  ✅ Ruta trazada para {net_name}: {len(path)} segmentos')",
        "                ",
        "                # --- Ancho de pista dinámico ---",
        "                # Pistas de alimentación más gruesas (0.8mm), señales normales (0.4mm)",
        "                track_width = 0.8 if any(x in net_name.upper() for x in ['VCC', 'GND', '+', 'PWR', 'BAT']) else 0.4",
        "                ",
        "                for j in range(len(path) - 1):",
        "                    coord1 = path[j]",
        "                    coord2 = path[j+1]",
        "                    track = pcbnew.PCB_TRACK(board)",
        "                    track.SetStart(pcbnew.VECTOR2I(mm_to_nm(coord1.x*RESOLUTION), mm_to_nm(coord1.y*RESOLUTION)))",
        "                    track.SetEnd(pcbnew.VECTOR2I(mm_to_nm(coord2.x*RESOLUTION), mm_to_nm(coord2.y*RESOLUTION)))",
        "                    track.SetWidth(mm_to_nm(track_width))",
        "                    track.SetLayer(pcbnew.F_Cu)",
        "                    track.SetNet(net)",
        "                    board.Add(track)",
        "            else:",
        "                print(f'  ⚠️ No se encontró camino para {net_name}')",
        "                failed_count += 1",
        "else:",
        "    print('ℹ️ Módulo pathfinding no disponible. Se omite el auto-enrutado.')",
        "    print('  📎 Las conexiones quedan como ratsnest; se pueden enrutar manualmente en KiCad.')",
        "",
        "# --- Validación DRC (Design Rules Check) ---",
        "def check_drc(board, min_clearance_mm=0.3):",
        "    print(f'🔍 Ejecutando DRC (Clearance: {min_clearance_mm}mm)...')",
        "    min_dist_nm = mm_to_nm(min_clearance_mm)",
        "    violations = 0",
        "    tracks = [t for t in board.GetTracks() if t.GetClass() == 'PCB_TRACK']",
        "    footprints = list(board.GetFootprints())",
        "    for track in tracks:",
        "        t_start = track.GetStart()",
        "        t_end = track.GetEnd()",
        "        t_width = track.GetWidth()",
        "        t_net = track.GetNetCode()",
        "        for fp in footprints:",
        "            for pad in fp.Pads():",
        "                if pad.GetNetCode() == t_net: continue",
        "                p_pos = pad.GetPosition()",
        "                # Distancia punto a segmento",
        "                seg_v_x = t_end.x - t_start.x",
        "                seg_v_y = t_end.y - t_start.y",
        "                pt_v_x = p_pos.x - t_start.x",
        "                pt_v_y = p_pos.y - t_start.y",
        "                seg_len_sq = seg_v_x**2 + seg_v_y**2",
        "                if seg_len_sq == 0: dist_sq = pt_v_x**2 + pt_v_y**2",
        "                else:",
        "                    t = max(0, min(1, (pt_v_x * seg_v_x + pt_v_y * seg_v_y) / float(seg_len_sq)))",
        "                    proj_x = int(t_start.x + t * seg_v_x)",
        "                    proj_y = int(t_start.y + t * seg_v_y)",
        "                    dist_sq = (p_pos.x - proj_x)**2 + (p_pos.y - proj_y)**2",
        "                dist = math.sqrt(dist_sq)",
        "                p_radius = min(pad.GetSize().x, pad.GetSize().y) / 2",
        "                t_radius = t_width / 2",
        "                if dist < (p_radius + t_radius + min_dist_nm):",
        "                    violations += 1",
        "    if violations > 0:",
        "        print(f'❌ DRC FALLÓ: {violations} violaciones detectadas (Posibles cortocircuitos).')",
        "    else:",
        "        print('✅ DRC PASÓ: Diseño seguro para CNC.')",
        "",
        "# --- Guardar la placa ---",
        "output_dir = '/mnt/out' if os.path.exists('/mnt/out') else os.path.dirname(os.path.abspath(__file__))",
        "output_filename = os.path.join(output_dir, 'circuito_generado.kicad_pcb')",
        "try:",
        "    check_drc(board)",
        "    pcbnew.SaveBoard(output_filename, board)",
        "    print(f'✅ PCB guardado en: {output_filename}')",
        "except Exception as e:",
        "    print(f'❌ Error guardando PCB: {e}', file=sys.stderr)",
        "    sys.exit(1)",
        "",
        "if PATHFINDING_AVAILABLE:",
        "    print(f'ROUTING_SUMMARY:Routed={routed_count},Failed={failed_count},Total={total_connections}')",
        "else:",
        "    print(f'ROUTING_SUMMARY:Routed=0,Failed=0,Total=0')",
        "",
        "if xvfb_proc: xvfb_proc.terminate()",
    ]

    # Escribir el script generado en el archivo de salida
    try:
        os.makedirs(os.path.dirname(output_script_path) or ".", exist_ok=True)
        with open(output_script_path, 'w') as f:
            f.write("\n".join(script_lines))
        print(json.dumps({"status": "success", "file": output_script_path}))
    except Exception as e:
        print(json.dumps({"status": "error", "message": f"Error escribiendo script de PCB: {e}"}))
        sys.exit(1)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Genera un script Python para crear un archivo KiCad PCB (.kicad_pcb).")
    parser.add_argument("--json", required=True, help="Ruta al archivo JSON de diseño.")
    parser.add_argument("--output", required=True, help="Ruta de salida para el script Python generado.")
    args = parser.parse_args()

    generate_pcb_script(args.json, args.output)