#!/usr/bin/env python3
"""
Genera un script Python que, al ser ejecutado dentro de la Consola de Scripting
de KiCad PCB Editor (pcbnew), crea un archivo .kicad_pcb con los componentes
colocados y las conexiones (ratsnest) definidas a partir de un JSON de diseño.
"""
import json
import argparse
import os
import sys

# Este script NO importa pcbnew directamente, ya que está diseñado para
# generar otro script que SÍ lo importará dentro de KiCad.

def generate_pcb_script(design_json_path, output_script_path, width=150, height=100, margin=25):
    """
    Crea un script Python para KiCad PCB Editor.
    """
    # Cargar el JSON de diseño
    try:
        with open(design_json_path, 'r') as f:
            design_data = json.load(f)
    except Exception as e:
        print(json.dumps({"status": "error", "message": f"Error leyendo JSON de diseño: {e}"}))
        sys.exit(1)

    components = design_data.get("components", [])
    netlist_data = design_data.get("netlist", [])

    # Construir un mapa de cuántos pines necesita cada componente (para fallback)
    pins_per_ref = {}
    for net_info in netlist_data:
        for node in net_info.get('nodes', []):
            parts = node.split('-')
            if len(parts) == 2:
                ref, pin = parts
                if ref not in pins_per_ref:
                    pins_per_ref[ref] = set()
                pins_per_ref[ref].add(pin)
    # Inyectar el mapa como dato en el script generado
    pins_per_ref_serializable = {k: sorted(list(v)) for k, v in pins_per_ref.items()}

    # Generar el contenido del script de KiCad
    script_lines = [
        "import os",
        "import json",
        "import sys",
        "import subprocess",
        "import time",
        "import math",
        "",
        "# --- Configuración de Entorno Gráfico (Headless) ---",
        "# Iniciamos Xvfb para que KiCad/pcbnew tenga un 'monitor' donde operar",
        "os.environ['DISPLAY'] = ':99'",
        "xvfb_proc = None",
        "try:",
        "    if os.system('pgrep Xvfb > /dev/null') != 0:",
        "        print('Iniciando servidor gráfico virtual (Xvfb)...', file=sys.stderr)",
        "        xvfb_proc = subprocess.Popen(['Xvfb', ':99', '-screen', '0', '1024x768x24', '-ac', '+extension', 'GLX', '+render', '-noreset'])",
        "        time.sleep(3) # Esperar a que Xvfb arranque",
        "        if xvfb_proc and xvfb_proc.poll() is not None:",
        "            print(f'Error: Xvfb terminó inesperadamente. Código: {xvfb_proc.returncode}', file=sys.stderr)",
        "            sys.exit(1)",
        "except Exception as e:",
        "    print(f'Error fatal al iniciar Xvfb: {e}', file=sys.stderr)",
        "    sys.exit(1)",
        "",
        "try:",
        "    print('Intentando importar pcbnew...', file=sys.stderr)",
        "    import pcbnew",
        "    print('pcbnew importado con éxito.', file=sys.stderr)",
        "except Exception as e:",
        "    print(f'Error: No se pudo importar pcbnew. Verifica la instalación de KiCad. Error: {e}', file=sys.stderr)",
        "    import traceback; traceback.print_exc(file=sys.stderr)",
        "    sys.exit(1)",
        "",
        "# --- Configuración de la Placa ---",
        f"BOARD_WIDTH_MM = {width}",
        f"BOARD_HEIGHT_MM = {height}",
        f"START_X_MM = {margin}",
        f"START_Y_MM = {margin}",
        "DEFAULT_SPACING = 20  # mm entre componentes",
        "",
        "# --- Helper para convertir mm a unidades internas de KiCad (nanómetros) ---",
        "def mm_to_nm(mm_val):",
        "    return int(mm_val * 1000000)",
        "",
        "# --- Crear una nueva placa ---",
        "board = pcbnew.BOARD()",
        "",
        "# --- Datos de componentes y netlist (inyectados desde el JSON original) ---",
        f"components_data = {json.dumps(components, indent=2)}",
        f"netlist_data = {json.dumps(netlist_data, indent=2)}",
        f"pins_per_ref = {json.dumps(pins_per_ref_serializable, indent=2)}",
        "",
        "# --- Helper: Crear footprint genérico con pads reales ---",
        "def create_generic_footprint(board, ref, pin_list, pos_x_nm, pos_y_nm):",
        "    fp = pcbnew.FOOTPRINT(board)",
        "    fp.SetReference(ref)",
        "    fp.SetPosition(pcbnew.VECTOR2I(pos_x_nm, pos_y_nm))",
        "    fp.SetLayer(pcbnew.F_Cu)",
        "    # Crear pads reales para cada pin (espaciados 2.54mm = paso THT estándar)",
        "    pad_pitch_nm = mm_to_nm(2.54)",
        "    pad_size_nm = mm_to_nm(1.6)",
        "    drill_nm = mm_to_nm(0.9)",
        "    n_pins = len(pin_list) if pin_list else 2",
        "    # Para componentes grandes (SoCs/ICs), distribuimos pads en dos filas (estilo DIP)",
        "    is_dual_row = n_pins > 4",
        "    row_spacing_nm = mm_to_nm(7.62) if n_pins <= 28 else mm_to_nm(15.24)",
        "",
        "    for idx, pin_num in enumerate(pin_list if pin_list else ['1', '2']):",
        "        pad = pcbnew.PAD(fp)",
        "        pad.SetNumber(str(pin_num))",
        "        pad.SetShape(pcbnew.PAD_SHAPE_CIRCLE)",
        "        pad.SetAttribute(pcbnew.PAD_ATTRIB_PTH)  # Through-hole",
        "        pad.SetSize(pcbnew.VECTOR2I(pad_size_nm, pad_size_nm))",
        "        pad.SetDrillSize(pcbnew.VECTOR2I(drill_nm, drill_nm))",
        "",
        "        if is_dual_row:",
        "            # Distribución en dos columnas",
        "            side = 1 if idx < (n_pins/2) else -1",
        "            row_idx = idx % (math.ceil(n_pins/2))",
        "            offset_x = int(side * row_spacing_nm / 2)",
        "            offset_y = int((row_idx - (n_pins/4.0)) * pad_pitch_nm)",
        "            pad.SetPosition(pcbnew.VECTOR2I(pos_x_nm + offset_x, pos_y_nm + offset_y))",
        "        else:",
        "            # Distribución en una línea (resistencias, leds, etc)",
        "            offset_x = int((idx - (n_pins - 1) / 2.0) * pad_pitch_nm) if n_pins > 1 else 0",
        "            pad.SetPosition(pcbnew.VECTOR2I(pos_x_nm + offset_x, pos_y_nm))",
        "",
        "        pad.SetLayerSet(pcbnew.LSET.PTHMask())",
        "        fp.Add(pad)",
        "    board.Add(fp)",
        "    return fp",
        "",
        "# --- Cálculo de Rejilla y Tamaño de Placa ---",
        "n_comp = len(components_data)",
        "min_margin = START_X_MM # START_X_MM ahora representa el margen mínimo deseado",
        "",
        "# Calcular el número de columnas y filas para la rejilla de componentes",
        "# Asegurarse de que haya al menos 1 columna",
        "cols_count = max(1, int((BOARD_WIDTH_MM - 2 * min_margin) // DEFAULT_SPACING))",
        "if cols_count > n_comp: cols_count = n_comp",
        "rows_count = math.ceil(n_comp / cols_count)",
        "",
        "# --- Fase de Atracción Lógica (Optimización de Placement) ---",
        "if n_comp > 2:",
        "    print('🧠 Optimizando posición de componentes por afinidad de red...', file=sys.stderr)",
        "    sorted_comps = []",
        "    remaining = list(components_data)",
        "    # Empezamos con el componente que tiene más pines (usualmente el integrado principal)",
        "    current = max(remaining, key=lambda c: len(pins_per_ref.get(c['ref'], [])))",
        "    sorted_comps.append(current)",
        "    remaining.remove(current)",
        "    ",
        "    while remaining:",
        "        last = sorted_comps[-1]",
        "        # Obtener nombres de redes conectadas al último componente colocado",
        "        last_nets = set()",
        "        for net in netlist_data:",
        "            nodes = net.get('nodes', [])",
        "            if any(node.startswith(last['ref'] + '-') for node in nodes):",
        "                last_nets.add(net.get('net_name') or net.get('netname'))",
        "        ",
        "        # Buscar el componente restante más 'atraído' (que comparte más redes)",
        "        best_candidate = None",
        "        max_shared = -1",
        "        for candidate in remaining:",
        "            cand_nets = set()",
        "            for net in netlist_data:",
        "                nodes = net.get('nodes', [])",
        "                if any(node.startswith(candidate['ref'] + '-') for node in nodes):",
        "                    cand_nets.add(net.get('net_name') or net.get('netname'))",
        "            ",
        "            shared_count = len(last_nets.intersection(cand_nets))",
        "            if shared_count > max_shared:",
        "                max_shared = shared_count",
        "                best_candidate = candidate",
        "        ",
        "        sorted_comps.append(best_candidate)",
        "        remaining.remove(best_candidate)",
        "    components_data = sorted_comps",
        "",
        "# --- Cálculo de Repulsión y Posicionamiento Final ---",
        "PUSH_FACTOR = 4.0  # Incrementado para dejar canales amplios para DeepPCB",
        "col_widths = [DEFAULT_SPACING for _ in range(cols_count)]",
        "row_heights = [DEFAULT_SPACING for _ in range(rows_count)]",
        "",
        "for i, comp in enumerate(components_data):",
        "    col = i % cols_count",
        "    row = i // cols_count",
        "    n_pins = len(pins_per_ref.get(comp['ref'], []))",
        "    # La repulsión hace que celdas con componentes complejos sean más grandes",
        "    required_space = DEFAULT_SPACING + (n_pins * PUSH_FACTOR)",
        "    if required_space > col_widths[col]: col_widths[col] = required_space",
        "    if required_space > row_heights[row]: row_heights[row] = required_space",
        "",
        "total_w = sum(col_widths)",
        "total_h = sum(row_heights)",
        "",
        "# Centrado dinámico considerando el espacio ganado por repulsión",
        "START_X_MM = max(min_margin, (BOARD_WIDTH_MM - total_w) / 2 + col_widths[0]/2)",
        "START_Y_MM = max(min_margin, (BOARD_HEIGHT_MM - total_h) / 2 + row_heights[0]/2)",
        "",
        "# --- Lógica de Espaciado Central (Anti-Congestión) ---",
        "CENTER_X, CENTER_Y = BOARD_WIDTH_MM / 2, BOARD_HEIGHT_MM / 2",
        "CENTER_PUSH = 12.0 # mm extra para alejar del centro",
        "",
        "final_positions = []",
        "curr_y = START_Y_MM",
        "max_reached_x, max_reached_y = BOARD_WIDTH_MM, BOARD_HEIGHT_MM",
        "",
        "for r in range(rows_count):",
        "    curr_x = START_X_MM",
        "    for c in range(cols_count):",
        "        idx = r * cols_count + c",
        "        if idx < n_comp:",
        "            # Empujar componentes hacia el exterior para dejar el centro libre",
        "            adj_x = curr_x - (CENTER_PUSH/2) if curr_x < CENTER_X else curr_x + (CENTER_PUSH/2)",
        "            adj_y = curr_y - (CENTER_PUSH/2) if curr_y < CENTER_Y else curr_y + (CENTER_PUSH/2)",
        "            final_positions.append((adj_x, adj_y))",
        "            ",
        "            if adj_x + 15 > max_reached_x: max_reached_x = adj_x + 15",
        "            if adj_y + 15 > max_reached_y: max_reached_y = adj_y + 15",
        "        if c < cols_count - 1:",
        "            curr_x += (col_widths[c] + col_widths[c+1]) / 2",
        "    if r < rows_count - 1:",
        "        curr_y += (row_heights[r] + row_heights[r+1]) / 2",
        "",
        "# --- Definir el contorno de la placa (Edge.Cuts) ---",
        "board_outline = pcbnew.PCB_SHAPE(board)",
        "board_outline.SetShape(pcbnew.SHAPE_T_RECT)",
        "board_outline.SetStart(pcbnew.VECTOR2I(0, 0))",
        "board_outline.SetEnd(pcbnew.VECTOR2I(mm_to_nm(max_reached_x), mm_to_nm(max_reached_y)))",
        "board_outline.SetLayer(pcbnew.Edge_Cuts)",
        "board.Add(board_outline)",
        "",
        "# --- Cargar y colocar Footprints (Huellas) ---",
        "footprints_by_ref = {}",
        "for i, comp in enumerate(components_data):",
        "    ref = comp['ref']",
        "    pin_list = pins_per_ref.get(ref, ['1', '2'])",
        "    if 'footprint' in comp and comp['footprint']:",
        "        footprint_name = comp['footprint']",
        "    else:",
        "        ctype = str(comp.get('type', '')).upper()",
        "        cval = str(comp.get('value', '')).lower()",
        "        # IMPORTANT: check capacitors/LEDs/pots BEFORE ICs to avoid 'IC' substring in 'ELECTROLYTIC','CERAMIC'",
        "        if ref.startswith('C') or 'CAP' in ctype:",
        "            footprint_name = 'Capacitor_THT:CP_Radial_D5.0mm_P2.50mm' if 'uf' in cval else 'Capacitor_THT:C_Disc_D5.0mm_W2.5mm_P5.00mm'",
        "        elif ref.startswith('D') or 'LED' in ctype or 'DIOD' in ctype:",
        "            footprint_name = 'LED_THT:LED_D5.0mm'",
        "        elif ref.startswith('RV') or 'POT' in ctype:",
        "            footprint_name = 'Potentiometer_THT:Potentiometer_Alps_RK163_Single_Horizontal'",
        "        elif ref.startswith('R'):",
        "            footprint_name = 'Resistor_THT:R_Axial_DIN0207_L6.3mm_D2.5mm_P7.62mm_Horizontal'",
        "        elif ref.startswith('Q') or 'TRANS' in ctype:",
        "            footprint_name = 'Package_TO_SOT_THT:TO-92_Inline'",
        "        elif ref.startswith('U') or 'IC' in ctype or ctype == 'MICROCONTROLLER':",
        "            npins = len(pin_list)",
        "            if npins < 4: npins = 8",
        "            if npins % 2 != 0: npins += 1",
        "            footprint_name = f'Package_DIP:DIP-{npins}_W7.62mm'",
        "        else:",
        "            footprint_name = 'Resistor_THT:R_Axial_DIN0207_L6.3mm_D2.5mm_P7.62mm_Horizontal'",
        "    ",
        "    # Usar posición calculada con lógica de repulsión y atracción",
        "    pos_x_mm, pos_y_mm = final_positions[i]",
        "    ",
        "    # Intentar cargar la huella desde las librerías de KiCad",
        "    pos_x_nm = mm_to_nm(pos_x_mm)",
        "    pos_y_nm = mm_to_nm(pos_y_mm)",
        "    try:",
        "        fp = None",
        "        footprint_lib_id = footprint_name.split(':', 1)",
        "        if len(footprint_lib_id) == 2:",
        "            lib_name, fp_name = footprint_lib_id",
        "            lib_path = f'/usr/share/kicad/footprints/{lib_name}.pretty'",
        "            import os as _os",
        "            if _os.path.exists(lib_path):",
        "                fp = pcbnew.FootprintLoad(lib_path, fp_name)",
        "            else:",
        "                print(f'  ⚠️ Librería no encontrada: {lib_path}')",
        "        ",
        "        if fp is None:",
        "            raise Exception(f'FootprintLoad devolvió None para {footprint_name}')",
        "        ",
        "        fp.SetReference(ref)",
        "        fp.SetPosition(pcbnew.VECTOR2I(pos_x_nm, pos_y_nm))",
        "        fp.SetLayer(pcbnew.F_Cu)",
        "        board.Add(fp)",
        "        footprints_by_ref[ref] = fp",
        "        print(f'✅ Footprint {ref} ({footprint_name}) colocado en ({pos_x_mm:.2f}, {pos_y_mm:.2f})')",
        "    except Exception as e:",
        "        print(f'⚠️ Fallback genérico para {ref}: {e}')",
        "        fp = create_generic_footprint(board, ref, pin_list, pos_x_nm, pos_y_nm)",
        "        footprints_by_ref[ref] = fp",
        "        print(f'📦 Footprint genérico {ref} con pads {pin_list} colocado en ({pos_x_mm:.2f}, {pos_y_mm:.2f})')",
        "",
        "# --- Crear Netlist y conectar Pads ---",
        "nets_by_name = {}",
        "for net_info in netlist_data:",
        "    net_name = net_info.get('net_name') or net_info.get('netname')",
        "    if net_name not in nets_by_name:",
        "        net = pcbnew.NETINFO_ITEM(board, net_name)",
        "        board.Add(net)",
        "        nets_by_name[net_name] = net",
        "    else:",
        "        net = nets_by_name[net_name]",
        "    ",
        "    for node in net_info['nodes']:",
        "        if '-' not in str(node):",
        "            print(f'  ⚠️ Saltando nodo inválido (formato incorrecto): {node}')",
        "            continue",
        "        ref, pin_num = node.split('-', 1)",
        "        if ref in footprints_by_ref:",
        "            fp = footprints_by_ref[ref]",
        "            pad = fp.FindPadByNumber(pin_num)",
        "            if not pad:",
        "                pnum_u = pin_num.upper()",
        "                if pnum_u == 'ANODE': pad = fp.FindPadByNumber('2') or fp.FindPadByNumber('A') or fp.FindPadByNumber('1')",
        "                elif pnum_u == 'CATHODE': pad = fp.FindPadByNumber('1') or fp.FindPadByNumber('K') or fp.FindPadByNumber('2')",
        "                elif pnum_u in ('POS', '+'): pad = fp.FindPadByNumber('2') or fp.FindPadByNumber('1')",
        "                elif pnum_u in ('NEG', '-'): pad = fp.FindPadByNumber('1') or fp.FindPadByNumber('2')",
        "                else:",
        "                    import re",
        "                    m = re.search(r'\\d+', pin_num)",
        "                    if m: pad = fp.FindPadByNumber(m.group(0))",
        "            if pad:",
        "                pad.SetNetCode(net.GetNetCode())",
        "            else:",
        "                print(f'Warning: Pad {pin_num} not found for {ref}.')",
        "        else:",
        "            print(f'Warning: Footprint {ref} not found in placed components for net {net_name}.')",
        "",
        "# --- Preparación para DeepPCB (Enrutado Externo) ---",
        "connections_count = 0",
        "for net_name, net in nets_by_name.items():",
        "    pads = [p for p in board.GetPads() if p.GetNetCode() == net.GetNetCode()]",
        "    if len(pads) >= 2: connections_count += (len(pads) - 1)",
        "print(f'Identificadas {connections_count} conexiones para enrutado externo.', file=sys.stderr)",
        "",
        "# --- Guardar la placa ---",
        "output_dir = '/mnt/out' if os.path.exists('/mnt/out') else os.path.dirname(os.path.abspath(__file__))",
        "output_filename = os.path.join(output_dir, 'circuito_generado.kicad_pcb')",
        "try:",
        "    pcbnew.SaveBoard(output_filename, board)",
        "    print(f'✅ PCB guardado en: {output_filename}')",
        "except Exception as e:",
        "    print(f'❌ Error guardando PCB: {e}', file=sys.stderr)",
        "    sys.exit(1)",
        "",
        "print(f'ROUTING_SUMMARY:Routed=0,Failed=0,Total={connections_count},DRC=0,Iterations=0')",
        "",
        "if xvfb_proc: xvfb_proc.terminate()",
    ]

    # Escribir el script generado en el archivo de salida
    try:
        os.makedirs(os.path.dirname(output_script_path) or ".", exist_ok=True)
        with open(output_script_path, 'w') as f:
            f.write("\n".join(script_lines))
        print(json.dumps({"status": "success", "file": output_script_path}))
    except Exception as e:
        print(json.dumps({"status": "error", "message": f"Error escribiendo script de PCB: {e}"}))
        sys.exit(1)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Genera un script Python para crear un archivo KiCad PCB (.kicad_pcb).")
    parser.add_argument("--json", required=True, help="Ruta al archivo JSON de diseño.")
    parser.add_argument("--output", required=True, help="Ruta de salida para el script Python generado.")
    parser.add_argument("--width", type=int, default=150, help="Ancho de la placa en mm.")
    parser.add_argument("--height", type=int, default=100, help="Alto de la placa en mm.")
    parser.add_argument("--margin", type=int, default=25, help="Margen inicial para componentes en mm.")
    args = parser.parse_args()

    generate_pcb_script(args.json, args.output, args.width, args.height, args.margin)